export const AssignmentTable = `CREATE TABLE IF NOT EXISTS assignment(
 id INT AUTO_INCREMENT PRIMARY KEY, 
 degree FLOAT, 
 link VARCHAR(255), 
 content_id INT NOT NULL,
 created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
  )`;

export const TakesAssignmentTable = `CREATE TABLE IF NOT EXISTS takes_assignment(
  id INT AUTO_INCREMENT PRIMARY KEY,
  assignment_grade FLOAT,
  student_id INT NOT NULL,
  content_id INT NOT NULL,
  FOREIGN KEY (student_id) REFERENCES student(s_id) ON DELETE CASCADE ON UPDATE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`;

// FOREIGN KEY (content_id) REFERENCES content(content id) ON DELETE CASCADE ON UPDATE CASCADE
