export const PaymentTable = `CREATE TABLE IF NOT EXIST payment(
id INT AUTO_INCREMENT PRIMARY KEY , img VARCHAR(100) NOT NULL, intiation_date DATE NOT NULL, student_id INT NOT NULL,admin_nid INT NOT NULL, 
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`;

export const ExtraPaymentTable = `CREATE TABLE IF NOT EXIST extra_payment(
id INT AUTO_INCREMENT PRIMARY KEY,
student_id INT NOT NULL,
course_id INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
  


)`;
