export const AssignmentTable = `CREATE TABLE IF NOT EXIST assignment(
id INT AUTO_INCREMENT PRIMARY KEY , degree FLOAT , link VARCHAR(255) , content_id INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`;

export const TakesAssignmentTable = `CREATE TABLE IF NOT EXIST takes_assignment(
id INT AUTO_INCREMENT PRIMARY KEY , assignment_grade FLOAT , student_id INT NOT NULL , content_id INT NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP)`;
